import json

path = '/home/sumit/Documents/GitHub/Train_POC/TTS/fish_s2pro_hinglish_audiobook_2_5_L4_LONG QT4.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 0: Markdown
nb['cells'][0]['source'] = [
    "# 🐟 S2-PRO (GGUF) — Long-Form Hinglish Audiobook Pipeline\\n",
    "## T4 GPU · s2.cpp Vulkan Inference · Smart Chunking\\n",
    "\\n",
    "**Model**: `rodrigomt/s2-pro-gguf` (Q8_0 Quantized)\\n",
    "**Runtime**: Google Colab · **NVIDIA T4 GPU**\\n",
    "**Features**:\\n",
    "- 🎯 High-speed pure C++ inference via `s2.cpp`\\n",
    "- ⚡ Vulkan GPU acceleration\\n",
    "- 🧠 Fits easily in 15GB VRAM (Q8_0 is ~6.11 GB)\\n",
    "- 📖 Smart sentence-boundary text chunking for long stories\\n",
    "- 🎙️ Reference audio voice cloning across all chunks\\n",
    "- 🌐 Hinglish (Devanagari + Latin script) fully supported\\n",
    "\\n",
    "**Workflow**: Cell 1→8 in order. No restarts needed.\\n",
    "\\n",
    "| Cell | Purpose |\\n",
    "|------|--------|\\n",
    "| 1 | Hardware audit (Vulkan support check) |\\n",
    "| 2 | Configuration |\\n",
    "| 3 | Upload text file (.txt) |\\n",
    "| 4 | Upload reference audio (optional) |\\n",
    "| 5 | **Build s2.cpp engine** (CMake/Vulkan) |\\n",
    "| 6 | Download GGUF weights |\\n",
    "| 7 | **S2 Synthesis** (chunked CLI pipeline) |\\n",
    "| 8 | Play & download output |\\n"
]

# Cell 1: Environment Audit
nb['cells'][1]['source'] = [
    "# ════════════════════════════════════════════════════════════\\n",
    "# CELL 1 — ENVIRONMENT & HARDWARE AUDIT\\n",
    "# ════════════════════════════════════════════════════════════\\n",
    "import os, sys, subprocess, platform, time\\n",
    "\\n",
    "SEP = \"═\" * 62\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  CELL 1 — ENVIRONMENT & HARDWARE AUDIT\")\\n",
    "print(f\"{SEP}\\n\")\\n",
    "\\n",
    "print(\"🐍 PYTHON\")\\n",
    "print(f\"   Version      : {sys.version.split()[0]}\")\\n",
    "print(f\"   Executable   : {sys.executable}\")\\n",
    "\\n",
    "print(f\"\\n💻 CPU & RAM\")\\n",
    "try:\\n",
    "    with open('/proc/meminfo') as f:\\n",
    "        mi = {l.split(':')[0]: l.split(':')[1].strip() for l in f}\\n",
    "    total_gb = int(mi['MemTotal'].split()[0])     / 1e6\\n",
    "    avail_gb = int(mi['MemAvailable'].split()[0]) / 1e6\\n",
    "    print(f\"   Host RAM     : {total_gb:.1f} GB ({avail_gb:.1f} GB available)\")\\n",
    "except Exception as e:\\n",
    "    print(f\"   /proc/meminfo: {e}\")\\n",
    "\\n",
    "print(f\"\\n⚡ GPU ACCELERATOR (Vulkan Target)\")\\n",
    "_has_gpu = False\\n",
    "try:\\n",
    "    smi = subprocess.check_output(\\n",
    "        ['nvidia-smi','--query-gpu=name,memory.total,driver_version',\\n",
    "         '--format=csv,noheader,nounits'],\\n",
    "        stderr=subprocess.DEVNULL).decode().strip()\\n",
    "    parts = [p.strip() for p in smi.split(\",\")]\\n",
    "    gpu_name = parts[0] if parts else \"Unknown\"\\n",
    "    gpu_vram = parts[1] if len(parts) > 1 else \"?\"\\n",
    "    gpu_driver = parts[2] if len(parts) > 2 else \"?\"\\n",
    "    print(f\"   GPU          : {gpu_name}\")\\n",
    "    print(f\"   VRAM         : {gpu_vram} MB\")\\n",
    "    print(f\"   Driver       : {gpu_driver}\")\\n",
    "    vram_mb = int(gpu_vram)\\n",
    "    _has_gpu = True\\n",
    "    if vram_mb >= 8000:\\n",
    "        print(f\"   ✅ Sufficient VRAM for Q8_0 weights (~6.1 GB + context)\")\\n",
    "    else:\\n",
    "        print(f\"   ⚠️  Low VRAM — might need Q6_K or CPU compilation.\")\\n",
    "except Exception:\\n",
    "    print(f\"   GPU          : none detected (Will fall back to CPU inference)\")\\n",
    "\\n",
    "print(f\"\\n🔧 TOOLS\")\\n",
    "for tool in ['git','cmake','ffmpeg','python3','curl']:\\n",
    "    try:\\n",
    "        path = subprocess.check_output(['which',tool],stderr=subprocess.DEVNULL).decode().strip()\\n",
    "        print(f\"   ✅ {tool:12s} → {path}\")\\n",
    "    except:\\n",
    "        print(f\"   ℹ️ {tool:12s} → Will be installed during dependencies.\")\\n",
    "\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  ✅ CELL 1 COMPLETE — Proceed to Cell 2\")\\n",
    "print(f\"{SEP}\")\\n"
]

# Cell 2: Config
nb['cells'][2]['source'] = [
    "# ════════════════════════════════════════════════════════════\\n",
    "# CELL 2 — CONFIGURATION\\n",
    "# ════════════════════════════════════════════════════════════\\n",
    "import os\\n",
    "\\n",
    "SEP = \"═\" * 62\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  CELL 2 — CONFIGURATION\")\\n",
    "print(f\"{SEP}\\n\")\\n",
    "\\n",
    "# ── EDIT THESE ────────────────────────────────────────────────\\n",
    "DO_INSTALL     = True           # False = skip engine build\\n",
    "MODEL_DIR      = '/content/models/s2-pro-gguf'\\n",
    "OUTPUT_DIR     = '/content/inference_outputs'\\n",
    "S2_BINARY      = '/content/s2.cpp/build/s2'\\n",
    "\\n",
    "# Model weights size targeting (Q8_0 recommended for Colab T4)\\n",
    "QUANT_LEVEL    = 's2-pro-q8_0.gguf'\\n",
    "\\n",
    "# Device: 0 = GPU Vulkan, -1 = CPU mode\\n",
    "VULKAN_DEVICE  = 0\\n",
    "\\n",
    "# ── VOICE CLONING ─────────────────────────────────────────────\\n",
    "PROMPT_TEXT    = 'नमस्कार। मैं हूँ आपका storyteller. आज की कहानी शुरू होती है एक ऐसी जगह से — जहाँ राज़ छुपे हैं, जहाँ सच और झूठ के बीच सिर्फ एक पतली सी लकीर है। सुनिए ध्यान से। क्योंकि यह कहानी सिर्फ सुनने की नहीं — महसूस करने की है.'\\n",
    "\\n",
    "# ── GENERATION PARAMS ─────────────────────────────────────────\\n",
    "TEMPERATURE    = 0.7\\n",
    "TOP_P          = 0.8\\n",
    "TOP_K          = 50\\n",
    "MAX_TOKENS     = 2048\\n",
    "\\n",
    "# ── LONG TEXT CHUNKING ─────────────────────────────────────────\\n",
    "CHUNK_SIZE     = 100            # Words per chunk (reduced slightly for s2.cpp max safety)\\n",
    "CROSSFADE_MS   = 50             # Crossfade overlap between chunks (ms)\\n",
    "# ──────────────────────────────────────────────────────────────\\n",
    "\\n",
    "os.makedirs(MODEL_DIR,  exist_ok=True)\\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\\n",
    "os.makedirs('/content/uploads', exist_ok=True)\\n",
    "\\n",
    "print(f\"\\n{'─'*40}\")\\n",
    "print(f\"   DO_INSTALL     : {DO_INSTALL}\")\\n",
    "print(f\"   MODEL_DIR      : {MODEL_DIR}/\")\\n",
    "print(f\"   WEIGHTS        : {QUANT_LEVEL}\")\\n",
    "print(f\"   VULKAN_DEVICE  : {VULKAN_DEVICE}\")\\n",
    "print(f\"   TEMPERATURE    : {TEMPERATURE}\")\\n",
    "print(f\"   MAX_TOKENS     : {MAX_TOKENS}\")\\n",
    "print(f\"   CHUNK_SIZE     : {CHUNK_SIZE} words\")\\n",
    "print(f\"{'─'*40}\")\\n",
    "\\n",
    "TEXT_TO_SYNTH   = \"नमस्ते! यह FishAudio S2-Pro का परीक्षण है।\"\\n",
    "REFERENCE_AUDIO = ''\\n",
    "\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  ✅ CELL 2 COMPLETE — Proceed to Cell 3\")\\n",
    "print(f\"{SEP}\")\\n"
]

# Cell 5: Build s2.cpp
nb['cells'][5]['source'] = [
    "# ════════════════════════════════════════════════════════════\\n",
    "# CELL 5 — BUILD ENGINE  (s2.cpp with Vulkan)\\n",
    "# ════════════════════════════════════════════════════════════\\n",
    "import os, sys, subprocess, time\\n",
    "\\n",
    "SEP = \"═\" * 62\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  CELL 5 — BUILDING S2.CPP VULKAN ENGINE\")\\n",
    "print(f\"{SEP}\\n\")\\n",
    "\\n",
    "if not DO_INSTALL:\\n",
    "    print(\"   ⏭️  DO_INSTALL = False — skipping.\\n\")\\n",
    "else:\\n",
    "    t0 = time.time()\\n",
    "    \\n",
    "    print(\"   📦 Installing system dependencies (cmake, vulkan-tools)...\")\\n",
    "    subprocess.run(['apt-get', 'update', '-qq'])\\n",
    "    subprocess.run(['apt-get', 'install', '-y', '-qq', 'cmake', 'libvulkan-dev', 'vulkan-tools', 'ffmpeg', 'build-essential', 'git'], capture_output=True)\\n",
    "    \\n",
    "    REPO_DIR = '/content/s2.cpp'\\n",
    "    if not os.path.exists(os.path.join(REPO_DIR, '.git')):\\n",
    "        print(\"   📥 Cloning rodrigomatta/s2.cpp...\")\\n",
    "        subprocess.run(['git', 'clone', '--recurse-submodules', 'https://github.com/rodrigomatta/s2.cpp.git', REPO_DIR])\\n",
    "    else:\\n",
    "        print(\"   ✅ Repo already cloned.\")\\n",
    "        \\n",
    "    print(\"   🔨 Compiling s2.cpp with Vulkan support (this takes 1-3 mins)...\")\\n",
    "    os.chdir(REPO_DIR)\\n",
    "    subprocess.run(['cmake', '-B', 'build', '-DCMAKE_BUILD_TYPE=Release', '-DS2_VULKAN=ON'])\\n",
    "    r = subprocess.run(['cmake', '--build', 'build', '--parallel', str(os.cpu_count())], capture_output=True, text=True)\\n",
    "    \\n",
    "    if r.returncode == 0 and os.path.exists('./build/s2'):\\n",
    "        print(f\"   ✅ Engine built successfully! ({time.time() - t0:.1f}s)\")\\n",
    "    else:\\n",
    "        print(f\"   ❌ Build failed! Check cmake logs:\\n{r.stderr[-500:]}\")\\n",
    "        raise RuntimeError(\"Failed to build s2.cpp renderer.\")\\n",
    "\\n",
    "    print(\"   📦 Installing huggingface-cli for model downloads...\")\\n",
    "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'huggingface_hub'])\\n",
    "    print(\"   ✅ huggingface_hub ready.\")\\n",
    "\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  ✅ CELL 5 COMPLETE — Proceed to Cell 6\")\\n",
    "print(f\"{SEP}\")\\n"
]

# Cell 6: Download Model
nb['cells'][6]['source'] = [
    "# ════════════════════════════════════════════════════════════\\n",
    "# CELL 6 — DOWNLOAD GGUF WEIGHTS\\n",
    "# ════════════════════════════════════════════════════════════\\n",
    "import os, sys, subprocess, time\\n",
    "\\n",
    "SEP = \"═\" * 62\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  CELL 6 — DOWNLOADING MODEL WEIGHTS\")\\n",
    "print(f\"{SEP}\")\\n",
    "\\n",
    "t0 = time.time()\\n",
    "print(f\"   📥 Downloading {QUANT_LEVEL} and tokenizer.json from rodrigomt/s2-pro-gguf...\")\\n",
    "cmd = [\\n",
    "    'huggingface-cli', 'download', 'rodrigomt/s2-pro-gguf',\\n",
    "    QUANT_LEVEL, 'tokenizer.json',\\n",
    "    '--local-dir', MODEL_DIR\\n",
    "]\\n",
    "proc = subprocess.run(cmd, capture_output=True, text=True)\\n",
    "if proc.returncode == 0:\\n",
    "    print(f\"   ✅ Download complete/verified ({time.time() - t0:.1f}s)\")\\n",
    "else:\\n",
    "    print(f\"   ❌ Download failed:\\n{proc.stderr}\")\\n",
    "    raise RuntimeError(\"Failed to download GGUF model.\")\\n",
    "\\n",
    "for f in [QUANT_LEVEL, 'tokenizer.json']:\\n",
    "    size = os.path.getsize(os.path.join(MODEL_DIR, f)) / 1e6\\n",
    "    print(f\"   📄 {f}: {size:.1f} MB\")\\n",
    "\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  ✅ CELL 6 COMPLETE — Proceed to Cell 7\")\\n",
    "print(f\"{SEP}\")\\n"
]

# Cell 7: Inference
nb['cells'][7]['source'] = [
    "# ════════════════════════════════════════════════════════════\\n",
    "# CELL 7 — S2 SYNTHESIS  (Chunked CLI Pipeline)\\n",
    "# ════════════════════════════════════════════════════════════\\n",
    "import os, sys, time, gc, re, glob, shlex, subprocess\\n",
    "import html as _html\\n",
    "import numpy as np\\n",
    "from IPython.display import display, HTML, clear_output\\n",
    "\\n",
    "SEP = \"═\" * 62\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(\"  CELL 7 — S2 SYNTHESIS  (VULKAN GPU · CHUNKED)\")\\n",
    "print(f\"{SEP}\\n\")\\n",
    "\\n",
    "if not os.path.exists(S2_BINARY):\\n",
    "    raise FileNotFoundError(f\"s2 binary not found at {S2_BINARY}. Please run Cell 5.\")\\n",
    "if not os.path.exists(os.path.join(MODEL_DIR, QUANT_LEVEL)):\\n",
    "    raise FileNotFoundError(f\"{QUANT_LEVEL} not found. Please run Cell 6.\")\\n",
    "\\n",
    "for f in glob.glob(os.path.join(OUTPUT_DIR, 'chunk_*.wav')):\\n",
    "    os.remove(f)\\n",
    "for f in glob.glob(os.path.join(OUTPUT_DIR, 'output_s2pro.wav')):\\n",
    "    os.remove(f)\\n",
    "\\n",
    "def chunk_text(text, max_words=100):\\n",
    "    sentences = re.split(r'(?<=[।.!?\\n])\\s*', text.strip())\\n",
    "    sentences = [s.strip() for s in sentences if s.strip()]\\n",
    "    chunks, current, current_wc = [], [], 0\\n",
    "    for sent in sentences:\\n",
    "        sent_wc = len(sent.split())\\n",
    "        if sent_wc > max_words:\\n",
    "            if current: chunks.append(' '.join(current)); current, current_wc = [], 0\\n",
    "            words = sent.split()\\n",
    "            for i in range(0, len(words), max_words): chunks.append(' '.join(words[i:i+max_words]))\\n",
    "            continue\\n",
    "        if current_wc + sent_wc > max_words and current:\\n",
    "            chunks.append(' '.join(current)); current = [sent]; current_wc = sent_wc\\n",
    "        else:\\n",
    "            current.append(sent); current_wc += sent_wc\\n",
    "    if current: chunks.append(' '.join(current))\\n",
    "    return chunks if chunks else [text.strip()]\\n",
    "\\n",
    "text_clean = TEXT_TO_SYNTH.replace('\\r\\n', '\\n').strip()\\n",
    "total_words = len(text_clean.split())\\n",
    "text_chunks = chunk_text(text_clean, max_words=CHUNK_SIZE)\\n",
    "num_chunks = len(text_chunks)\\n",
    "\\n",
    "print(f\"📄 Text split into {num_chunks} chunk(s)  ({total_words} total words)\")\\n",
    "for ci, ch in enumerate(text_chunks):\\n",
    "    preview = ch[:60].replace('\\n',' ') + ('...' if len(ch) > 60 else '')\\n",
    "    print(f\"   Chunk {ci+1}: {len(ch.split())} words — {preview}\")\\n",
    "\\n",
    "t0 = time.time()\\n",
    "chunk_wavs = []\\n",
    "\\n",
    "for ci, chunk_text in enumerate(text_chunks):\\n",
    "    chunk_num = ci + 1\\n",
    "    chunk_t0 = time.time()\\n",
    "    chunk_wav_path = os.path.join(OUTPUT_DIR, f'chunk_{chunk_num:04d}.wav')\\n",
    "    \\n",
    "    print(f\"\\n⏳ Synthesizing chunk {chunk_num}/{num_chunks}...\")\\n",
    "    cmd = [\\n",
    "        S2_BINARY,\\n",
    "        '-m', os.path.join(MODEL_DIR, QUANT_LEVEL),\\n",
    "        '-t', os.path.join(MODEL_DIR, 'tokenizer.json'),\\n",
    "        '-v', str(VULKAN_DEVICE),\\n",
    "        '-max-tokens', str(MAX_TOKENS),\\n",
    "        '-temp', str(TEMPERATURE),\\n",
    "        '-top-p', str(TOP_P),\\n",
    "        '-top-k', str(TOP_K),\\n",
    "        '-o', chunk_wav_path,\\n",
    "        '-text', chunk_text.replace('\\n', ' ')\\n",
    "    ]\\n",
    "    if REFERENCE_AUDIO and os.path.exists(REFERENCE_AUDIO):\\n",
    "        cmd.extend(['-pa', REFERENCE_AUDIO])\\n",
    "        if PROMPT_TEXT.strip():\\n",
    "            cmd.extend(['-pt', PROMPT_TEXT.replace('\\n', ' ')])\\n",
    "            \\n",
    "    proc = subprocess.run(cmd, capture_output=True, text=True)\\n",
    "    \\n",
    "    if proc.returncode == 0 and os.path.exists(chunk_wav_path):\\n",
    "        print(f\"   ✅ Chunk {chunk_num} complete ({time.time() - chunk_t0:.1f}s)\")\\n",
    "        chunk_wavs.append(chunk_wav_path)\\n",
    "    else:\\n",
    "        print(f\"   ❌ Chunk {chunk_num} failed!\")\\n",
    "        print(proc.stderr)\\n",
    "        raise RuntimeError(f\"s2.cpp inference failed on chunk {chunk_num}\")\\n",
    "\\n",
    "print(f\"\\n{SEP}\")\\n",
    "print(f\"  ✅ ALL {num_chunks} CHUNKS SYNTHESIZED\")\\n",
    "\\n",
    "if num_chunks == 1:\\n",
    "    import shutil\\n",
    "    OUTPUT_WAV_PATH = os.path.join(OUTPUT_DIR, 'output_s2pro.wav')\\n",
    "    shutil.move(chunk_wavs[0], OUTPUT_WAV_PATH)\\n",
    "else:\\n",
    "    import librosa\\n",
    "    import soundfile as sf\\n",
    "    all_audio = []\\n",
    "    target_sr = None\\n",
    "    for wpath in chunk_wavs:\\n",
    "        data, sr = librosa.load(wpath, sr=None, mono=True)\\n",
    "        if target_sr is None: target_sr = sr\\n",
    "        elif sr != target_sr: data = librosa.resample(data, orig_sr=sr, target_sr=target_sr)\\n",
    "        all_audio.append(data)\\n",
    "        \\n",
    "    crossfade_samples = int(target_sr * CROSSFADE_MS / 1000)\\n",
    "    if crossfade_samples < 1: crossfade_samples = 1\\n",
    "    \\n",
    "    result = all_audio[0]\\n",
    "    for i in range(1, len(all_audio)):\\n",
    "        nxt = all_audio[i]\\n",
    "        if len(result) >= crossfade_samples and len(nxt) >= crossfade_samples:\\n",
    "            fade_out = np.linspace(1, 0, crossfade_samples)\\n",
    "            fade_in  = np.linspace(0, 1, crossfade_samples)\\n",
    "            overlap = result[-crossfade_samples:] * fade_out + nxt[:crossfade_samples] * fade_in\\n",
    "            result = np.concatenate([result[:-crossfade_samples], overlap, nxt[crossfade_samples:]])\\n",
    "        else:\\n",
    "            result = np.concatenate([result, nxt])\\n",
    "\\n",
    "    OUTPUT_WAV_PATH = os.path.join(OUTPUT_DIR, 'output_s2pro.wav')\\n",
    "    sf.write(OUTPUT_WAV_PATH, result, target_sr)\\n",
    "\\n",
    "print(f\"  🎉 Final concatenated output: {OUTPUT_WAV_PATH}\")\\n",
    "print(f\"  Total time: {time.time() - t0:.1f}s\")\\n",
    "print(f\"{SEP}\\n\")\\n"
]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print("Notebook updated successfully.")
